config/routes.rb
FirehoseHbs::Application.routes.draw do

   root 'static_pages#index'
   resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	# can write a method here that you can use in the rails console
	# def about
	# 	self.emotion +”, “+self.learned
	# end

	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	def index
		@pics = Pic.all
		# your'e grabbing many pics here... 
		#@pics is a variable.... where you access it is in the view.... capital P is important
	end

	def new
		@pic = Pic.new
		# one new row or one new Pic
		# think of the @pic as a temp variable
	end
 
 # for the create button / save button 
	 def create
	 		@pic = Pic.create(pic_params)
	 		redirect_to pics_path 
	 		# think of the @pic as a temp variable
	 end



	 private

# creating a function or a method 
	 def  pic_params
	 		params.require(:pic).permit(:lesson, :emotion, :learned, :image)
	 		#can specify what things you want htem to be abel to change
	 		# grab all the things from this pic thing.
	 end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirehoseHbs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width">
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
       <%= link_to('Firehose App', root_path, :class => 'brand' ) %>

 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->

        <ul class="nav">
        	<li>
        		<%= link_to 'My App', pics_path %>
        	</li>

          <li>
            <%= link_to 'Create new', new_pic_path %>
          </li>
          <!-- looked at the rake routes to hook up the application -->


        </ul>

      </div>
 
    </div>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
	<br/>
<% @pics.each do |pic| %>
<!-- .each is basically a loop that allows you to go through all of the pics database -->
<div class="span4 boxy text-center">
<!-- # for each pics, do something and be able toa ccess what that thing is -->
		<h1 class='h1-custom'> Tea type: <%= pic.lesson %> </h1>
		<br/>

		<%= image_tag pic.image %>
		
		<h2 class='h2-custom'>
			Tea type: <%= pic.emotion %>
			<br/>
			Characteristics: <%= pic.learned %>
			<br/>
		</h2>
	<!-- in this section display what the lesson is...   -->
</div>
<% end %>

app/views/pics/new.html.erb
<div class = "span6 offset3 text-center boxy">
	<h1 class = "h1-custom">
		Upload another tea type
	</h1>
	<br/>


		<%= simple_form_for @pic do |f| %>

			<!-- about to do some form stuff & i want all the magic there ...  -->
			<!-- @pic is basically a blank... and use "this" as an object and connect it to the form -->
			<!-- the "do and end" is a way to have aceess to "f" -->
				<%= f.input :lesson, :label => 'Tea type #', :placeholder => '1,2, etc' %>
				<%= f.input :image, :label => 'Picture' %>
				<%= f.input :emotion , :label => 'Name of tea?', :placeholder => 'e.g., green' %>
				<%= f.input :learned, :label => 'Characteristics?', :placeholder => 'high caffeine, fermented' %>
				<!-- customizing the labels in the bootstrap_...tab -->

				<%= submit_tag 'Save', :class => 'btn btn-warning btn-large'%>


		<% end %>
	<br/>

</div>

app/views/static_pages/index.html.erb
<div class ="span6 offset3 boxy text-center">
	<h1 class="h1-custom"> Blend your own tea </h1>
	<br/>

	<h2 class='h2-custom'> This is a test page </h2>
	<%= link_to 'Launch', pics_path, :class => 'btn btn-warning btn-large'%>
</div>